### ISSUE TITLE
proper input

### ISSUE THREAD

**Issue by mvolkmann** [nablaa/rushhour-solver-prolog#1]
I know you wrote this a LONG time ago and may not remember, but does this look like the correct way to create and supply input to this program? I suspect I may need to use different values for the car colors.

```prolog
  Cars = [
    car(x, (0, 0), (1, 0)),
    car(p, (0, 1), (0, 3)),
    car(r, (1, 2), (2, 2)),
    car(o, (0, 4), (0, 5)),
    car(b, (3, 1), (3, 3)),
    car(c, (4, 4), (5, 4)),
    car(g, (2, 5), (4, 5)),
    car(y, (5, 0), (5, 2))
  ],
  Board = board(6, 6, (5, 3), Cars),
  solve_dfs_print(Board),
  % or this: solve_astar_print(Board).
```

**Comment by mvolkmann** [comment]
I had some errors above. I think the red car needs to have the color "x" and some of my coordinates were wrong. Now I have this:

```prolog
  % X goes left to right from 0 to 5.
  % Y goes top to bottom from 0 to 5.
  Cars = [
    car(l, (0, 0), (1, 0)), % l for lime green
    car(p, (0, 1), (0, 3)), % p for purple
    car(x, (1, 2), (2, 2)), % target car has color x
    car(o, (0, 4), (0, 5)), % o for orange
    car(b, (3, 1), (3, 3)), % b for blue
    car(c, (4, 4), (5, 4)), % c for cyan (light blue)
    car(g, (2, 5), (4, 5)), % g for green
    car(y, (5, 0), (5, 2))  % y for yellow
  ],
  Exit = (5, 2),
  Size = 6,
  Board = board(Size, Size, Exit, Cars),
  % solve_dfs_print(Board),
  solve_astar_print(Board).
```

Doing it this way, the program runs for about 12 seconds and then stops with the error "Stack limit (1.0Gb) exceeded.

Can you confirm whether you were able to get the dfs or astar approaches to work?

**Comment by mvolkmann** [comment]
Actual the `solve_dfs_print` rule is working for me now! But it doesn't find the shortest solution. It contains many repetitive moves.

**Comment by nablaa** [comment]
Nice to hear you find this old project of mine useful! And good to hear you got the code working in the end.

Unfortunately I don't remember the details of what went into this and don't remember if the repetitive moves are a known issue in the DFS implementation.
